# who will find it :)

In [1]:
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px
import ast 
from collections import Counter

In [2]:
old_df = pd.read_csv('application_data.csv')

In [3]:
df=old_df[['TARGET','CODE_GENDER','FLAG_OWN_CAR','FLAG_OWN_REALTY','DAYS_EMPLOYED','ORGANIZATION_TYPE','NAME_CONTRACT_TYPE','OCCUPATION_TYPE','CNT_FAM_MEMBERS','NAME_INCOME_TYPE','REGION_POPULATION_RELATIVE','NAME_HOUSING_TYPE','NAME_FAMILY_STATUS','NAME_EDUCATION_TYPE','CNT_CHILDREN','AMT_INCOME_TOTAL','AMT_GOODS_PRICE','AMT_CREDIT']].copy()
df

TARGET CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  DAYS_EMPLOYED  \
0            1           M            N               Y           -637   
1            0           F            N               N          -1188   
2            0           M            Y               Y           -225   
3            0           F            N               Y          -3039   
4            0           M            N               Y          -3038   
...        ...         ...          ...             ...            ...   
307506       0           M            N               N           -236   
307507       0           F            N               Y         365243   
307508       0           F            N               Y          -7921   
307509       1           F            N               Y          -4786   
307510       0           F            N               N          -1262   

             ORGANIZATION_TYPE NAME_CONTRACT_TYPE OCCUPATION_TYPE  \
0       Business Entity Type 3         Cash loans        Laborers   
1                       School         Cash loans      Core staff   
2                   Government    Revolving loans        Laborers   
3       Business Entity Type 3         Cash loans        Laborers   
4                     Religion         Cash loans      Core staff   
...                        ...                ...             ...   
307506                Services         Cash loans     Sales staff   
307507                     XNA         Cash loans             NaN   
307508                  School         Cash loans        Managers   
307509  Business Entity Type 1         Cash loans        Laborers   
307510  Business Entity Type 3         Cash loans        Laborers   

        CNT_FAM_MEMBERS      NAME_INCOME_TYPE  REGION_POPULATION_RELATIVE  \
0                   1.0               Working                    0.018801   
1                   2.0         State servant                    0.003541   
2                   1.0               Working                    0.010032   
3                   2.0               Working                    0.008019   
4                   1.0               Working                    0.028663   
...                 ...                   ...                         ...   
307506              1.0               Working                    0.032561   
307507              1.0             Pensioner                    0.025164   
307508              1.0               Working                    0.005002   
307509              2.0  Commercial associate                    0.005313   
307510              2.0  Commercial associate                    0.046220   

        NAME_HOUSING_TYPE    NAME_FAMILY_STATUS  \
0       House / apartment  Single / not married   
1       House / apartment               Married   
2       House / apartment  Single / not married   
3       House / apartment        Civil marriage   
4       House / apartment  Single / not married   
...                   ...                   ...   
307506       With parents             Separated   
307507  House / apartment                 Widow   
307508  House / apartment             Separated   
307509  House / apartment               Married   
307510  House / apartment               Married   

                  NAME_EDUCATION_TYPE  CNT_CHILDREN  AMT_INCOME_TOTAL  \
0       Secondary / secondary special             0          202500.0   
1                    Higher education             0          270000.0   
2       Secondary / secondary special             0           67500.0   
3       Secondary / secondary special             0          135000.0   
4       Secondary / secondary special             0          121500.0   
...                               ...           ...               ...   
307506  Secondary / secondary special             0          157500.0   
307507  Secondary / secondary special             0           72000.0   
307508               Higher education             0          153000.0   
307509  Secondary / se

In [4]:
df.dropna(inplace=True)
df

TARGET CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  DAYS_EMPLOYED  \
0            1           M            N               Y           -637   
1            0           F            N               N          -1188   
2            0           M            Y               Y           -225   
3            0           F            N               Y          -3039   
4            0           M            N               Y          -3038   
...        ...         ...          ...             ...            ...   
307504       0           F            N               Y          -7258   
307506       0           M            N               N           -236   
307508       0           F            N               Y          -7921   
307509       1           F            N               Y          -4786   
307510       0           F            N               N          -1262   

             ORGANIZATION_TYPE NAME_CONTRACT_TYPE OCCUPATION_TYPE  \
0       Business Entity Type 3         Cash loans        Laborers   
1                       School         Cash loans      Core staff   
2                   Government    Revolving loans        Laborers   
3       Business Entity Type 3         Cash loans        Laborers   
4                     Religion         Cash loans      Core staff   
...                        ...                ...             ...   
307504           Self-employed         Cash loans     Sales staff   
307506                Services         Cash loans     Sales staff   
307508                  School         Cash loans        Managers   
307509  Business Entity Type 1         Cash loans        Laborers   
307510  Business Entity Type 3         Cash loans        Laborers   

        CNT_FAM_MEMBERS      NAME_INCOME_TYPE  REGION_POPULATION_RELATIVE  \
0                   1.0               Working                    0.018801   
1                   2.0         State servant                    0.003541   
2                   1.0               Working                    0.010032   
3                   2.0               Working                    0.008019   
4                   1.0               Working                    0.028663   
...                 ...                   ...                         ...   
307504              1.0               Working                    0.022625   
307506              1.0               Working                    0.032561   
307508              1.0               Working                    0.005002   
307509              2.0  Commercial associate                    0.005313   
307510              2.0  Commercial associate                    0.046220   

        NAME_HOUSING_TYPE    NAME_FAMILY_STATUS  \
0       House / apartment  Single / not married   
1       House / apartment               Married   
2       House / apartment  Single / not married   
3       House / apartment        Civil marriage   
4       House / apartment  Single / not married   
...                   ...                   ...   
307504  House / apartment             Separated   
307506       With parents             Separated   
307508  House / apartment             Separated   
307509  House / apartment               Married   
307510  House / apartment               Married   

                  NAME_EDUCATION_TYPE  CNT_CHILDREN  AMT_INCOME_TOTAL  \
0       Secondary / secondary special             0          202500.0   
1                    Higher education             0          270000.0   
2       Secondary / secondary special             0           67500.0   
3       Secondary / secondary special             0          135000.0   
4       Secondary / secondary special             0          121500.0   
...                               ...           ...               ...   
307504  Secondary / secondary special             0          153000.0   
307506  Secondary / secondary special             0          157500.0   
307508               Higher education             0          153000.0   
307509  Secondary / se

## Encoding data

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import classification_report,plot_confusion_matrix, accuracy_score,confusion_matrix
from sklearn.preprocessing import OrdinalEncoder
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
 
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['NAME_HOUSING_TYPE'])
 
# printing label
label

array([1, 1, 1, ..., 1, 1, 1])

## Split data

In [6]:
y = df['TARGET']
df.drop('TARGET',axis=1, inplace=True)

all_cat_columns = df.select_dtypes(['object']).columns
df[all_cat_columns] = df[all_cat_columns].apply(lambda x: pd.factorize(x)[0])

X=df
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

## Create model : logistic regression 

In [7]:
lm1 = LogisticRegression().fit(X_train,y_train)

pred1 = lm1.predict(X_test)

Real_Values1 = np.array(y_test)
print("Logistic Regression Model")
print(Real_Values1)
print(pred1)
print("\nconfusion_matrix:\n")
print(confusion_matrix(y_test,pred1))
print("\nmodel's accuracy:\n") 
lm1.score(X_test, y_test) 

Logistic Regression Model
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]

confusion_matrix:

[[57682     0]
 [ 5588     0]]

model's accuracy:



0.9116801011537854

In [8]:
X.columns

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'DAYS_EMPLOYED',
       'ORGANIZATION_TYPE', 'NAME_CONTRACT_TYPE', 'OCCUPATION_TYPE',
       'CNT_FAM_MEMBERS', 'NAME_INCOME_TYPE', 'REGION_POPULATION_RELATIVE',
       'NAME_HOUSING_TYPE', 'NAME_FAMILY_STATUS', 'NAME_EDUCATION_TYPE',
       'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE', 'AMT_CREDIT'],
      dtype='object')

In [9]:
y

0         1
1         0
2         0
3         0
4         0
         ..
307504    0
307506    0
307508    0
307509    1
307510    0
Name: TARGET, Length: 210899, dtype: int64

In [10]:
df['TARGET'].value_counts()

KeyError: 'TARGET'

In [ ]:
lm1.coef_

In [ ]:
lm1.intercept_

## first row 
#### Actual = 1 
#### Model pred = 0 

In [ ]:
a=(-9.15645353)*(1)+(-2.58539288)*(0)+(-2.70554987)*(1)+(3.16459439)*(-637)+(-1.02816479)*(0)+(-2.83479711)*(0)
+(-4.09774623)*(0)+(-2.08146396)*(1.0)+(-5.11548429)*(0)+(-1.83193509)*(0.018801)+(-2.40170841)*(0)+(-1.15656034)*(0)+(-3.44162409)*(0)
+(-4.81745498)*(0)+(-5.80586544)*(202500)+(-4.09397887)*(351000)+(2.50968722)*(406597.5)+lm1.intercept_
a

In [ ]:
y = 1 / (1+np.exp((a)))
y

## second row 
#### Actual = 0
#### Model pred = 0 

In [ ]:
b=(-9.15645353)*(0)+(-2.58539288)*(0)+(-2.70554987)*(0)+( 3.16459439)*(-1188)+(-1.02816479)*(1)+(-2.83479711)*(0)
+(-4.09774623)*(1)+(-2.08146396)*(2.0)+(-5.11548429)*(1)+(-1.83193509)*(0.003541)+(-2.40170841)*(0)+(-1.15656034)*(1)+(-3.44162409)*(1)
+(-4.81745498)*(0)+(-5.80586544)*(270000)+(-4.09397887)*(1129500)+(2.50968722)*(1293502.5)+lm1.intercept_

In [ ]:
y = 1 / (1+np.exp((b)))
y

--------------------------------

In [ ]:
print("Training set score: {:.3f}".format(lm1.score(X_train,y_train)))
print("Test set score: {:.3f}".format(lm1.score(X_train,y_train)))
import statsmodels.api as sm
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary())